baseurl: "https://leomao.github.io/"
languageCode: "en"
theme: "hucore"
canonifyurls: true
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
author: "Leo Mao"
title: "0/1 World"
disqusshortname: ""
copyright: 'Leo Mao © 2017-2018 | <a href="http://github.com/leomao/hucore" target="_blank">Hucore theme</a> & <a href="http://gohugo.io" target="_blank">Hugo</a> ♥'

taxonomies:
  category: "categories"
  tag: "tags"

permalinks:
  post: "/:year/:month/:slug/"

params:
  author: "Leo Mao"
  sharingicons: false
  katex: true
  keywords:
    - math
    - programming
    - learning
  social:
    - url: "https://github.com/leomao"
      fa_icon: "fab fa-github"
    - url: "/index.xml"
      fa_icon: "fas fa-rss"
